import { CurrencyType } from "../types/currencies";

export const Currencies: CurrencyType = {
  EUR: { name: "Euro", symbol: "€", decimal: ",", position: "pre" },
  USD: { name: "United States dollar", symbol: "$", decimal: ".", position: "pre" },
  CAD: { name: "Canadian dollar", symbol: "$", decimal: ".", position: "pre" },
  HKD: { name: "Hong Kong dollar", symbol: "$", decimal: ".", position: "pre" },
  ISK: { name: "Icelandic króna", symbol: "kr", decimal: ",", position: "post" },
  PHP: { name: "Philippine peso", symbol: "₱", decimal: ".", position: "pre" },
  DDK: { name: "Danish krone", symbol: "kr.", decimal: ",", position: "post" },
  HUF: { name: "Hungarian forint", symbol: "Ft", decimal: ",", position: "post" },
  CZK: { name: "Czech koruna", symbol: "Kč", decimal: ",", position: "post" },
  AUD: { name: "Australian dollar", symbol: "$", decimal: ".", position: "pre" },
  RON: { name: "Romanian leu", symbol: "L", decimal: ",", position: "post" },
  SEK: { name: "Swedish krona", symbol: "kr", decimal: ",", position: "post" },
  IDR: { name: "Indonesian rupiah", symbol: "Rp", decimal: ",", position: "pre" },
  INR: { name: "Indian rupee", symbol: "₹", decimal: ".", position: "pre" },
  BRL: { name: "Brazilian real", symbol: "R$", decimal: ",", position: "pre" },
  RUB: { name: "Russian ruble", symbol: "₽", decimal: ",", position: "pre" },
  HRK: { name: "Croatian kuna", symbol: "kn", decimal: ",", position: "post" },
  JPY: { name: "Japanese yen", symbol: "¥", decimal: ".", position: "pre" },
  TBH: { name: "Thai baht", symbol: "฿", decimal: ".", position: "pre" },
  CHF: { name: "Swiss franc", symbol: "Fr.", decimal: ",", position: "post" },
  SGD: { name: "Singapore dollar", symbol: "$", decimal: ".", position: "pre" },
  PLN: { name: "Polish złoty", symbol: "zł", decimal: ",", position: "pre" },
  BGN: { name: "Bulgarian lev", symbol: "Лв.", decimal: ",", position: "pre" },
  TRY: { name: "Turkish lira", symbol: "₺", decimal: ".", position: "pre" },
  CNY: { name: "Chinese renminbi", symbol: "¥", decimal: ".", position: "pre" },
  NOK: { name: "Norwegian krone", symbol: "kr", decimal: ".", position: "post" },
  NZD: { name: "New Zealand dollar", symbol: "$", decimal: ".", position: "pre" },
  ZAR: { name: "South African rand", symbol: "R", decimal: ".", position: "pre" },
  MXN: { name: "Mexican peso", symbol: "$", decimal: ".", position: "pre" },
  ILS: { name: "Israeli shekel", symbol: "₪", decimal: ".", position: "pre" },
  GBP: { name: "Pound Sterling", symbol: "£", decimal: ".", position: "pre" },
  KRW: { name: "South Korean won", symbol: "₩", decimal: ".", position: "pre" },
  MYR: { name: "Malaysian ringgit", symbol: "RM", decimal: ".", position: "pre" },
};
