import { CurrencyType } from "../types/currencies";

export const Currencies: CurrencyType = {
  EUR: { name: "Euro", symbol: "€", position: "pre" },
  USD: { name: "United States dollar", symbol: "$", position: "pre" },
  CAD: { name: "Canadian dollar", symbol: "$", position: "pre" },
  HKD: { name: "Hong Kong dollar", symbol: "$", position: "pre" },
  ISK: { name: "Icelandic króna", symbol: "kr", position: "post" },
  PHP: { name: "Philippine peso", symbol: "₱", position: "pre" },
  DDK: { name: "Danish krone", symbol: "kr.", position: "post" },
  HUF: { name: "Hungarian forint", symbol: "Ft", position: "post" },
  CZK: { name: "Czech koruna", symbol: "Kč", position: "post" },
  AUD: { name: "Australian dollar", symbol: "$", position: "pre" },
  RON: { name: "Romanian leu", symbol: "L", position: "post" },
  SEK: { name: "Swedish krona", symbol: "kr", position: "post" },
  IDR: { name: "Indonesian rupiah", symbol: "Rp", position: "pre" },
  INR: { name: "Indian rupee", symbol: "₹", position: "pre" },
  BRL: { name: "Brazilian real", symbol: "R$", position: "pre" },
  RUB: { name: "Russian ruble", symbol: "₽", position: "pre" },
  HRK: { name: "Croatian kuna", symbol: "kn", position: "post" },
  JPY: { name: "Japanese yen", symbol: "¥", position: "pre" },
  TBH: { name: "Thai baht", symbol: "฿", position: "pre" },
  CHF: { name: "Swiss franc", symbol: "Fr.", position: "post" },
  SGD: { name: "Singapore dollar", symbol: "$", position: "pre" },
  PLN: { name: "Polish złoty", symbol: "zł", position: "pre" },
  BGN: { name: "Bulgarian lev", symbol: "Лв.", position: "pre" },
  TRY: { name: "Turkish lira", symbol: "₺", position: "pre" },
  CNY: { name: "Chinese renminbi", symbol: "¥", position: "pre" },
  NOK: { name: "Norwegian krone", symbol: "kr", position: "post" },
  NZD: { name: "New Zealand dollar", symbol: "$", position: "pre" },
  ZAR: { name: "South African rand", symbol: "R", position: "pre" },
  MXN: { name: "Mexican peso", symbol: "$", position: "pre" },
  ILS: { name: "Israeli shekel", symbol: "₪", position: "pre" },
  GBP: { name: "Pound Sterling", symbol: "£", position: "pre" },
  KRW: { name: "South Korean won", symbol: "₩", position: "pre" },
  MYR: { name: "Malaysian ringgit", symbol: "RM", position: "pre" },
};
